# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wednesday ETC…
email: wedetc@dreadserver.com
description: > # this means to ignore newlines until "baseurl:"
  Wednesday ETC… Come to our open mic session and get a free recording of your performance #OpenMic #RecordingSession #WednesdayNight #Dublin

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: wednesdayetc
github_username:  tomdread

# Build settings
markdown: kramdown
