# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wednesday ETC…
email: wedetc@dreadserver.com
description: > # this means to ignore newlines until "baseurl:"
 <strong>Wednesday ETC… Open Mic Recording Session… </strong>Every Wednesday 9pm, The International Basement, Wicklow Street, Dublin, Ireland. Come to our open mic session and get a free recording of your performance #OpenMic #RecordingSession #WednesdayNight #TheInterNationalBar #Dublin

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.wednesdayetc.com" # the base hostname & protocol for your site
twitter_username: wednesdayetc
github_username:  tomdread

# Build settings
markdown: kramdown
